import type { EmailBlock } from "../types/email";

/** 与主题令牌常见落点一致，用于扫描是否需展示「跟随/解除」条（无绑定时多数路径为 free） */
const EXTRA_BY_TYPE: Partial<Record<EmailBlock["type"], string[]>> = {
  emailRoot: [
    "props.backgroundColor",
    "props.border",
    "props.padding",
    "props.gap",
    "props.gapMode",
    "wrapperStyle.backgroundImage.src",
    "wrapperStyle.backgroundImage.alt",
    "wrapperStyle.backgroundImage.link",
    "wrapperStyle.backgroundImage.border",
    "wrapperStyle.backgroundImage.borderRadius",
  ],
  layout: [
    "props.gap",
    "props.gapMode",
    "props.direction",
    "wrapperStyle.backgroundColor",
    "wrapperStyle.border",
    "wrapperStyle.borderRadius",
    "wrapperStyle.padding",
    "wrapperStyle.placement.horizontal",
    "wrapperStyle.placement.vertical",
    "wrapperStyle.backgroundImage.src",
    "wrapperStyle.backgroundImage.border",
    "wrapperStyle.backgroundImage.borderRadius",
  ],
  text: [
    "props.color",
    "props.fontFamily",
    "props.fontSize",
    "wrapperStyle.backgroundColor",
    "wrapperStyle.border",
    "wrapperStyle.borderRadius",
    "wrapperStyle.padding",
  ],
  image: [
    "wrapperStyle.backgroundImage.src",
    "wrapperStyle.backgroundImage.alt",
    "wrapperStyle.backgroundImage.link",
    "wrapperStyle.backgroundImage.border",
    "wrapperStyle.backgroundImage.borderRadius",
    "wrapperStyle.backgroundColor",
    "wrapperStyle.border",
    "wrapperStyle.borderRadius",
    "wrapperStyle.padding",
  ],
  button: [
    "props.text",
    "props.link",
    "props.buttonStyle.backgroundColor",
    "props.buttonStyle.textColor",
    "props.buttonStyle.width",
    "props.buttonStyle.widthMode",
    "props.buttonStyle.fontFamily",
    "props.buttonStyle.fontSize",
    "props.buttonStyle.border",
    "props.buttonStyle.borderRadius",
    "wrapperStyle.backgroundColor",
    "wrapperStyle.border",
    "wrapperStyle.padding",
  ],
  divider: ["props.color", "props.lineWidth", "props.lineWidthMode", "props.height", "wrapperStyle.padding"],
  progress: [
    "props.trackColor",
    "props.fillColor",
    "props.barWidth",
    "props.barWidthMode",
    "props.barHeight",
    "props.barBorderRadius",
    "props.value",
    "props.max",
    "wrapperStyle.padding",
    "wrapperStyle.height",
    "wrapperStyle.heightMode",
  ],
  grid: [
    "props.gap",
    "props.cellWidth",
    "props.cellWidthMode",
    "props.cellHeight",
    "props.cellHeightMode",
    "props.columns",
    "wrapperStyle.backgroundColor",
    "wrapperStyle.border",
    "wrapperStyle.padding",
    "wrapperStyle.height",
    "wrapperStyle.heightMode",
  ],
  icon: [
    "props.src",
    "props.link",
    "props.color",
    "props.size",
    "wrapperStyle.padding",
  ],
};

export function collectInspectorBindingStripePaths(block: EmailBlock): string[] {
  const s = new Set<string>();
  for (const k of Object.keys(block.bindings ?? {})) s.add(k);
  for (const p of EXTRA_BY_TYPE[block.type] ?? []) s.add(p);
  return [...s];
}
